<?xml version="1.0" encoding="UTF-8"?>

<!-- ALVARO VILLANOVA AHLROTH -->

<!DOCTYPE pokedex [
    <!ELEMENT pokedex (pokemon+)>
    <!ELEMENT pokemon (name, types, abilities, baseStats, experience, legendary?)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT types (type+)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT abilities (ability+)>
    <!ELEMENT ability (#PCDATA)>
    <!ELEMENT baseStats (HP, ATK, DEF)>
    <!ELEMENT HP (#PCDATA)>
    <!ELEMENT ATK (#PCDATA)>
    <!ELEMENT DEF (#PCDATA)>
    <!ELEMENT experience (#PCDATA)>
    <!ELEMENT legendary EMPTY>
]>

<pokedex>
    <pokemon>
        <name>Beedrill</name>
        <types>
            <type>Bicho</type>
            <type>Volador</type>
        </types>
        <abilities>
            <ability>Fortaleza</ability>
            <ability>Doble Ataque</ability>
        </abilities>
        <baseStats>
            <HP>64</HP>
            <ATK>32</ATK>
            <DEF>27</DEF>
        </baseStats>
        <experience>400</experience>
    </pokemon>
    <pokemon>
        <name>Mewtwo</name>
        <types>
            <type>Psiquico</type>
        </types>
        <abilities>
            <ability>Psico Rayo</ability>
            <ability>Cabezaso</ability>
            <ability>Corte</ability>
        </abilities>
        <baseStats>
            <HP>666</HP>
            <ATK>420</ATK>
            <DEF>69</DEF>
        </baseStats>
        <experience>5678</experience>
        <legendary></legendary>
    </pokemon>
</pokedex>