<?xml version="1.0" encoding="UTF-8"?>

<!-- EJ5
Unos programadores necesitan estructurar la información que intercambiarán los ficheros de sus aplicaciones para lo cual han determinado los requisitos siguientes.

Los ficheros deben tener un elemento <listafacturas>
Dentro de la lista debe haber una o más facturas.
Las facturas tienen un atributo fecha que es optativo.
Toda factura tiene un emisor, que es un elemento obligatorio y que debe tener un atributo cif que es obligatorio. Dentro de emisor debe haber un elemento nombre, que es obligatorio y puede o no haber un elemento volumenventas.
Toda factura debe tener un elemento pagador, el cual tiene exactamente la misma estructura que emisor.
Toda factura tiene un elemento importe. -->

<!DOCTYPE listafacturas [
    <!ELEMENT listafacturas (factura+)>

    <!ELEMENT factura (emisor, pagador, importe)>
    <!ATTLIST factura fecha CDATA #IMPLIED>

    <!ELEMENT emisor (nombreEmisor, volumenVentasEmisor?)>
    <!ELEMENT nombreEmisor (#PCDATA)>
    <!ELEMENT volumenVentasEmisor (#PCDATA)>
    <!ATTLIST emisor cif CDATA #REQUIRED >

    <!ELEMENT pagador (nombrePagador, volumenVentasPagador?)>
    <!ELEMENT nombrePagador (#PCDATA)>
    <!ELEMENT volumenVentasPagador (#PCDATA)>
    <!ATTLIST pagador cif CDATA #REQUIRED >

    <!ELEMENT importe (#PCDATA)>
]>
<listafacturas>
    <factura fecha="01/01/1979">

        <emisor cif="5154">
            <nombreEmisor>loquesea</nombreEmisor>
            <volumenVentasEmisor>200</volumenVentasEmisor>
        </emisor>

        <pagador cif="1599">
            <nombrePagador>Lorem, ipsum dolor.</nombrePagador>
        </pagador>

        <importe>500</importe>
        
    </factura>

    <factura>
        <emisor cif="5154">
            <nombreEmisor>loquesea</nombreEmisor>
            <volumenVentasEmisor>200</volumenVentasEmisor>
        </emisor>
        <pagador cif="1599">
            <nombrePagador>Lorem, ipsum dolor.</nombrePagador>
        </pagador>
        <importe>500</importe>
    </factura>

</listafacturas>