<?xml version="1.0" encoding="UTF-8"?>

<!-- EJ6
Un instituto necesita registrar los cursos y alumnos que estudian en él y necesita una DTD para comprobar los documentos XML de los programas que utiliza:

Tiene que haber un elemento raíz listacursos. Tiene que haber uno o más cursos.
Un curso tiene uno o más alumnos
Todo alumno tiene un DNI, un nombre y un apellido, puede que tenga segundo apellido o no.
Un alumno escoge una lista de asignaturas donde habrá una o más asignaturas. Toda asignatura tiene un nombre, un atributo código y un profesor.
Un profesor tiene un NRP (Número de Registro Personal), un nombre y un apellido (también puede tener o no un segundo apellido). -->

<!DOCTYPE listacursos [
    <!ELEMENT listacursos (curso+)>

    <!ELEMENT curso (alumno+)>

    <!ELEMENT alumno (DNI, nombre, apellido, segundoApellido?, listaAsignaturas)>
    <!ELEMENT DNI (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT segundoApellido (#PCDATA)>

    <!ELEMENT listaAsignaturas (asignatura+)>

    <!ELEMENT asignatura (nombreAsignatura, profesor)>
    <!ATTLIST asignatura codigo CDATA #REQUIRED>
    <!ELEMENT nombreAsignatura (#PCDATA)>

    <!ELEMENT profesor (NRP, nombreProfesor, apellidoProfesor, segundoApellidoProfesor?)>
    <!ELEMENT NRP (#PCDATA)>
    <!ELEMENT nombreProfesor (#PCDATA)>
    <!ELEMENT apellidoProfesor (#PCDATA)>
    <!ELEMENT segundoApellidoProfesor (#PCDATA)>
]>
<listacursos>
    <curso>
        <alumno>
            <DNI>14586</DNI>
            <nombre>15947</nombre>
            <apellido>Lorem ipsum dolor sit.</apellido>
            <listaAsignaturas>
                <asignatura codigo="158">
                    <nombreAsignatura>SI</nombreAsignatura>
                    <profesor>
                        <NRP>18789</NRP>
                        <nombreProfesor>
                            Lorem, ipsum dolor.
                        </nombreProfesor>
                        <apellidoProfesor>
                            Lorem ipsum dolor sit.
                        </apellidoProfesor>
                    </profesor>
                </asignatura>
            </listaAsignaturas>
        </alumno>
    </curso>
</listacursos>