<?xml version="1.0" encoding="UTF-8"?>

<!-- EJ7
Se desea crear un formato de intercambio de datos para una empresa mayorista de libros con el fin de que sus distintos programas puedan manejar la información interna. El formato de archivo debe tener la siguiente estructura:
El elemento raíz es «operaciones».
Dentro de «operaciones» hay uno o más elementos «operacion».
Una «operacion» puede ser «venta», «compra», o cualquier combinación y secuencia de ellas, pero debe haber al menos una.
Una venta tiene dentro un elemento «titulosvendidos». Dentro de «titulosvendidos» se almacenan estos datos:
Uno o más elementos «título».
La cantidad total de libros vendidos.
Puede haber un elemento «entregado» que indique si la entrega se ha realizado.
Debe haber un elemento importe con un atributo obligatorio llamado «moneda».
Una compra tiene dentro un elemento «tituloscomprados». Dentro de él hay esto:
Uno o más elementos «titulo»
Un «proveedor».
Una fecha de compra, que debe desglosarse en elementos día, mes y año -->

<!DOCTYPE operaciones [

    <!ELEMENT operaciones (operacion+)>
    <!ELEMENT operacion (venta | compra)+>
    <!ELEMENT venta (titulosvendidos)>
    <!ELEMENT titulosvendidos (titulo+,totalvendidos,entregado?,importe+)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT totalvendidos (#PCDATA)>
    <!ELEMENT entregado (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>
        <!ATTLIST importe moneda CDATA #REQUIRED >
    <!ELEMENT compra (tituloscomprados)>
    <!ELEMENT tituloscomprados (tituloC+,proveedor,fechacompra)>
    <!ELEMENT tituloC (#PCDATA)>
    <!ELEMENT proveedor (#PCDATA)>
    <!ELEMENT fechacompra (dia,mes,anio)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
]>  

<operaciones>
    <operacion>
        <venta>
            <titulosvendidos>
                <titulo></titulo>
                <titulo></titulo>
                <totalvendidos></totalvendidos>
                <entregado></entregado>
                <importe moneda=""></importe>
            </titulosvendidos>
        </venta>
        <compra>
            <tituloscomprados>
                <tituloC></tituloC>
                <proveedor></proveedor>
                <fechacompra>
                    <dia></dia>
                    <mes></mes>
                    <anio></anio>
                </fechacompra>
            </tituloscomprados>
        </compra>
    </operacion>
    <operacion>
        <venta>
            <titulosvendidos>
                <titulo></titulo>
                <totalvendidos></totalvendidos>
                <entregado></entregado>
                <importe moneda=""></importe>
            </titulosvendidos>
        </venta>
    </operacion>
</operaciones>
