<?xml version="1.0" encoding="UTF-8"?>

<!-- Crea un fichero XML con DTD integrado que cumpla los siguientes requisitos
1. Elemento raíz concesionario
2. concesionario está compuesto de coches (al menos uno)
3. Los coches tienen marca, modelo, numero  de puertas y plazas
4. Los coches tienen un atributo obligatorio color
5. Los coches pueden ser eléctricos o no
6. Cada coche tiene una lista de extras (puede no haber extras)
7. El extra se compone de nombre, descripción(opcional) y precio
8. Los coches pueden ser automáticos o no -->

<!DOCTYPE concesionario [
    <!ELEMENT concesionario (coche+)>
    <!ELEMENT coche (marca, modelo, puertas, plazas, electrico?, automatico?, extras?)>
        <!ATTLIST coche color CDATA >
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT puertas (#PCDATA)>
    <!ELEMENT plazas (#PCDATA)>
    <!ELEMENT electrico EMPTY>
    <!ELEMENT automatico EMPTY>
    <!ELEMENT extras (extra+)>
    <!ELEMENT extra (nombre, descripcion?, precio)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>

<concesionario>
    <coche color="negro">
        <marca></marca>
        <modelo></modelo>
        <puertas></puertas>
        <plazas></plazas>
    </coche>

    <coche>
        <marca></marca>
        <modelo></modelo>
        <puertas></puertas>
        <plazas></plazas>
        <electrico />
        <extras>
            <extra>
                <nombre></nombre>
                <precio></precio>
            </extra>
            <extra>
                <nombre></nombre>
                <precio></precio>
            </extra>
            <extra>
                <nombre></nombre>
                <precio></precio>
            </extra>
        </extras>
    </coche>
</concesionario>